# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = ["amdgpu"];
    };
    kernelModules = [ "kvm-amd" "88x2bu" "asus-wmi-sensors" ];
    extraModulePackages = [
  	(config.boot.kernelPackages.rtl88x2bu.overrideAttrs (old: {
	  prePatch = old.prePatch + ''
	    substituteInPlace Makefile --replace "CONFIG_CONCURRENT_MODE = n" "CONFIG_CONCURRENT_MODE = y"
	    '';
	}))
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/de65fb5c-b35e-45d6-9c7d-276e50d831a7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F43-C811";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e650a71b-5b41-41f5-b858-b16dd903db66"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    brillo.enable = true;
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl.extraPackages = with pkgs; [
  	rocm-opencl-icd
	amdvlk
	libva
	];
    pulseaudio = {
  	enable = true;
	package = pkgs.pulseaudioFull;
	extraConfig = "
	load-module module-switch-on-connect
	";
    };
    bluetooth.enable = true;
  };
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
