include dark-theme.conf

tab_bar_align center
tab_bar_edge   top
shell /usr/bin/bash

symbol_map U+0E00-U+0E7F Tlwg Mono
modify_font cell_width +1

modify_font underline_position +2
modify_font underline_thickness 150%
modify_font strikethrough_position 2px

font_size 13
font_family      family='Iosevka Nerd Font Mono' style=SemiBold
bold_font        family='Iosevka Nerd Font Mono' style=Bold
italic_font      family='Iosevka Nerd Font Mono' style='SemiBold Italic'
bold_italic_font family='Iosevka Nerd Font Mono' style='Bold Italic'
