#!/usr/bin/env bash
## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
export TerminalEmulator=alacritty

## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
    FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
    BACKGROUND=$(xrdb -query | grep 'background:' | awk '{print $NF}')
    BLACK=$(xrdb -query | grep 'color0:' | awk '{print $NF}')
    RED=$(xrdb -query | grep 'color1:' | awk '{print $NF}')
    GREEN=$(xrdb -query | grep 'color2:' | awk '{print $NF}')
    YELLOW=$(xrdb -query | grep 'color3:' | awk '{print $NF}')
    BLUE=$(xrdb -query | grep 'color4:' | awk '{print $NF}')
    MAGENTA=$(xrdb -query | grep 'color5:' | awk '{print $NF}')
    CYAN=$(xrdb -query | grep 'color6:' | awk '{print $NF}')
    WHITE=$(xrdb -query | grep 'color7:' | awk '{print $NF}')
}
getcolors
# Configurations --------------------------------------------#
workspaces() {
    name=1
    for monitor in $(bspc query -M); do
        bspc monitor "${monitor}" -n "$name" -d '' '' '' '' ''
        ((name++))
    done
}


workspaces

bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.50

bspc config focused_border_color "#81D4FA"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false
# bspc config border_radius 5

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r '*:*'

# 1 > browsers
declare -a browsers=(Chromium Edge Microsoft-edge edge firefox Google-chrome Firefox firefox)
for i in "${browsers[@]}"; do
    bspc rule -a "$i" desktop='^1' follow=on focus=on
done

# 2 > code
declare -a code=(Neovide nvim neovim Neovim neovide Geany code-oss Visual-Studio-Code Code VSCode code vscode visual-studio-code)
for i in "${code[@]}"; do
    bspc rule -a "$i" desktop='^2' follow=on focus=on
done

# 3 > terminal
bspc rule -a Zsh desktop='^3' follow=on focus=on

# 4 > File stuff
declare -a comm=(Thunar ranger)
for i in "${comm[@]}"; do
    bspc rule -a "$i" desktop='^4' follow=on focus=on
done

# 5 > Discord and comuniccation
declare -a files=(discord Discord OBS OBS-Studio obs)
for i in "${files[@]}"; do
    bspc rule -a "$i" desktop='^5' follow=on focus=on
done

## Autostart -------------------------------------------------#

# Kill if already running
declare -a killlist=(xsettingsd sxhkd dunst ksuperkey networkctl)
for i in "${!killlist[@]}"; do
    pkill "${killlist[$i]}"
done


# Lauch xsettingsd daemon
xsettingsd &


# Lauch keybindings daemon
sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &

bash "$HOME/.config/bspwm/polybar/checkforupdate.sh" &

xmodmap -e 'remove lock = Caps_Lock'
setxkbmap -layout us,th -option grp:caps_toggle,grp_led:caps
numlockx on
# Fix cursor
xsetroot -cursor_name left_ptr
# Restore wallpaper
bash "$HOME/.fehbg"

# Start bspwm scripts
bspcolors
bspbar
bspdunst
border &
bspfloat &
