#!/usr/bin/env bash
## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
export TerminalEmulator=alacritty


bash "$HOME/.screenlayout/checkmons.sh" &
## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
    FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
    BACKGROUND=$(xrdb -query | grep 'background:' | awk '{print $NF}')
    BLACK=$(xrdb -query | grep 'color0:' | awk '{print $NF}')
    RED=$(xrdb -query | grep 'color1:' | awk '{print $NF}')
    GREEN=$(xrdb -query | grep 'color2:' | awk '{print $NF}')
    YELLOW=$(xrdb -query | grep 'color3:' | awk '{print $NF}')
    BLUE=$(xrdb -query | grep 'color4:' | awk '{print $NF}')
    MAGENTA=$(xrdb -query | grep 'color5:' | awk '{print $NF}')
    CYAN=$(xrdb -query | grep 'color6:' | awk '{print $NF}')
    WHITE=$(xrdb -query | grep 'color7:' | awk '{print $NF}')
}
getcolors
# Configurations --------------------------------------------#
bspc monitor -d '' '' '' '' '' ''

bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.50

bspc config focused_border_color "#425F57"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$BACKGROUND"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r '*:*'

declare -a files=(discord obs)
for i in "${files[@]}"; do
    bspc rule -a "$i" desktop='^5' follow=on focus=on
done

## Autostart -------------------------------------------------#

# Kill if already running
declare -a killlist=(xsettingsd sxhkd dunst ksuperkey networkctl)
for i in "${!killlist[@]}"; do
    pkill "${killlist[$i]}"
done


# Lauch xsettingsd daemon
xsettingsd &


sudo pkill udiskie
exec udiskie --automount --notify --tray &
# Lauch keybindings daemon
sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &


xmodmap -e 'remove lock = Caps_Lock'
setxkbmap -layout us,th -option grp:caps_toggle,grp_led:caps
numlockx on
# Fix cursor
xsetroot -cursor_name left_ptr
# Restore wallpaper
bash "$HOME/.fehbg"

# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
bspdunst
bspborder &
bspfloat &

brillo -c -S 2


bash "$HOME/.config/bspwm/polybar/checkforupdate.sh" &
