return {
  -- {
  --   "nvimtools/none-ls.nvim", -- none-ls is null-ls from community
  --   event = { "BufReadPre", "BufNewFile" },
  --   config = function()
  --     -- import null-ls plugin
  --     local null_ls = require("null-ls")
  --     -- code action sources
  --     local diagnostics = null_ls.builtins.diagnostics
  --     -- hover sources
  --
  --     -- configure null_ls
  --     null_ls.setup({
  --       -- setup formatters & linters
  --       on_init = function(new_client, _)
  --         new_client.offset_encoding = "utf-16"
  --       end,
  --       sources = {
  --         diagnostics.codespell,
  --         diagnostics.markdownlint,
  --         diagnostics.ktlint,
  --         diagnostics.todo_comments,
  --       },
  --     })
  --   end,
  -- },
}
