#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

## wlogout actions

# Ask for confirmation
cdialog() {
  dialog Confirm? "Are You Sure?"
}

if [[ "$1" == '--shutdown' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    loginctl poweroff
  else
    exit
  fi
elif [[ "$1" == '--reboot' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    loginctl reboot
  else
    exit
  fi
elif [[ "$1" == '--hibernate' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    loginctl hibernate
  else
    exit
  fi
elif [[ "$1" == '--lock' ]]; then
  playerctl pause
  swaylock
elif [[ "$1" == '--suspend' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    playerctl pause
    loginctl hybrid-sleep
  else
    exit
  fi
elif [[ "$1" == '--logout' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    loginctl terminate-session $(loginctl session-status | grep $(whoami) | awk '{print $1}')
  else
    exit
  fi
fi
