#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

## wlogout actions

# Ask for confirmation
cdialog () {
    yad --title='Confirm?' --borders=15 --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

if [[ "$1" == '--shutdown' ]]; then
    cdialog
    if [[ "$?" == 0 ]]; then
        loginctl poweroff
    else
        exit
    fi
elif [[ "$1" == '--reboot' ]]; then
    cdialog
    if [[ "$?" == 0 ]]; then
        loginctl reboot
    else
        exit
    fi
elif [[ "$1" == '--hibernate' ]]; then
    cdialog
    if [[ "$?" == 0 ]]; then
        loginctl hibernate
    else
        exit
    fi
elif [[ "$1" == '--lock' ]]; then
    swaylock
elif [[ "$1" == '--suspend' ]]; then
    cdialog
    if [[ "$?" == 0 ]]; then
        mpc -q pause
        pulsemixer --mute
        ~/.config/hypr/scripts/lockscreen
        loginctl suspend
    else
        exit
    fi
elif [[ "$1" == '--logout' ]]; then
    cdialog
    if [[ "$?" == 0 ]]; then
        swaymsg exit
    else
        exit
    fi
fi
