# vim: ft=tmux
set -g mode-style "fg=#eee8d5,bg=#262626"

set -g message-style "fg=#eee8d5,bg=#262626"
set -g message-command-style "fg=#eee8d5,bg=#262626"

set -g pane-border-style "fg=#073642"
set -g pane-active-border-style "fg=#eee8d5"

set -g status "on"
set -g status-interval 1
set -g status-justify "absolute-centre"
set -g status-style "fg=#586e75,bg=#262626"
set -g status-position "top"
set -g status-bg "#151515"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left ""
set -g status-right ""
