# set -g default-terminal "tmux"
set-option -g default-terminal "xterm"
# set -ga terminal-overrides ",*256col*:Tc"
# set-option -sa terminal-features ',alacritty:RGB'
set -sg terminal-overrides ",*:RGB"
# set-option -ga terminal-overrides ',alacritty:Tc'
# set -ga terminal-overrides ",xterm-256color:Tc"
# Set Default Shell
set -g default-command /bin/zsh
# action key
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0
# set-option -g focus-events on

#### Key bindings

set-window-option -g mode-keys vi

bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"
#bind t send-key C-t
# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

#### basic settings

set -g mouse on
#set-option utf8-default on
# set-option -g mouse-select-pane
#set-window-option -g utf8 on
# set-option -g history-limit 64096

# set -sg escape-time 10

#### COLOUR

set-option -s set-clipboard on
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

set-option -g update-environment "DISPLAY WAYLAND_DISPLAY SSH_AUTH_SOCK"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-yank'
## Restore Neovim sessions
## Restore Panes
## Restore last saved environment (automatically)
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'nvim'

# set -g @yank_selection 'primary' # or 'secondary' or 'clipboard'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
