[default]
extend-ignore-re = [
    # *sigh* this just isn't worth the cost of fixing
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
    "(?s)(#|//|--)\\s*spellchecker:off.*?\\n\\s*(#|//|--)\\s*spellchecker:on",
]
