#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## launch dunst with alt config

CONFIG="$HOME/.config/hypr/dunst"

if [[ ! `pidof dunst` ]]; then
    dunst -config ${CONFIG}
else
    pkill dunst
    dunst -config ${CONFIG}
fi
