#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs
## Edited for Garuda Linux by yurihikari

# Kill already running process
_ps=(waybar dunst)
for _prs in "${_ps[@]}"; do
    if [[ `pidof ${_prs}` ]]; then
        killall -9 ${_prs}
    fi
done

# Start gnome keyring
exec gnome-keyring-daemon --daemonize --start --components=gpg,pkcs11,secrets,ssh &

# Polkit agent
# if [[ ! `pidof xfce-polkit` ]]; then
# 	/usr/lib/xfce-polkit/xfce-polkit &
# fi
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Set wallpaper
swaybg --output '*' --mode fill --image /home/vaz/.config/sway/backgrounds/flatppuccin_4k_macchiato.png &

# Apply themes
# ~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &
~/.config/hypr/scripts/idlelock &

# Start network manager applet
nm-applet --indicator &
rm /run/user/1000/pipewire-0.lock &
pipewire &
systemctl --user restart pipewire.service &


if [ -z "$XDG_RUNTIME_DIR" ]; then
    export XDG_RUNTIME_DIR=/run/user/$(id -u)
fi

export STATUS_FILE="$XDG_RUNTIME_DIR/touchpad.status"

printf "true" > "$STATUS_FILE"

ID="$(pactl get-source-mute @DEFAULT_SOURCE@ | grep yes | cut -f1)"
if [[ -n $ID ]]; then
    sleep 0.1
else
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
fi

exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY &
exec hash dbus-update-activation-environment 2>/dev/null && \
    dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY &
