#!/usr/bin/env bash

get_backlight() {
	printf "%.0f\n" "$(light -G)"
}
notify_user() {
	get_backlight >"$SWAYSOCK.wob"
}

inc_backlight() {
	brillo -q -A 10 && notify_user
}

dec_backlight() {
	brillo -q -U 5 && notify_user
}

if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
