#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Script To Manage Speaker Volume For Archcraft (in Wayland).

iDIR="$HOME/.config/sway/scripts/icons"
notify_cmd='notify-send -h string:x-canonical-private-synchronous:sys-notify-volume -u low'

# Get Volume
get_volume() {
  printf "%'.0f\n" "$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | sed 's/\%//')"
}

# Get icons
get_icon() {
	current="$(get_volume)"
	if [[ "$current" -eq "0" ]]; then
		icon="$iDIR/volume-mute.svg"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		icon="$iDIR/volume-low.svg"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		icon="$iDIR/volume-mid.svg"
	elif [[ ("$current" -ge "60") ]]; then
		icon="$iDIR/volume-high.svg"
	fi
}

notify_user() {
	get_volume >"$SWAYSOCK.wob"
}

# Increase Volume
inc_volume() {
	ISMUTED="$(pactl get-sink-mute @DEFAULT_SINK@ | grep yes)"
	if [[ -n $ISMUTED ]]; then
		pactl set-sink-mute @DEFAULT_SINK@ toggle
	fi
	pactl set-sink-volume @DEFAULT_SINK@ +2% && notify_user
}

# Decrease Volume
dec_volume() {
	ISMUTED="$(pactl get-sink-mute @DEFAULT_SINK@ | grep yes)"
	if [[ -n $ISMUTED ]]; then
		pactl set-sink-mute @DEFAULT_SINK@ toggle
	fi
	pactl set-sink-volume @DEFAULT_SINK@ -2% && notify_user
}

# Toggle Mute
toggle_mute() {
	ISMUTED="$(pactl get-sink-mute @DEFAULT_SINK@ | grep yes)"
	if [[ -n $ISMUTED ]]; then
      pactl set-sink-mute @DEFAULT_SINK@ toggle && get_icon && ${notify_cmd} -i "$icon" "Unmute"
	else
      pactl set-sink-mute @DEFAULT_SINK@ toggle && ${notify_cmd} -i "$iDIR/volume-mute.svg" "Mute"
	fi
}

# Toggle Mic
toggle_mic() {
	ISMUTED="$(pactl get-source-mute @DEFAULT_SOURCE@ | grep yes)"
	if [[ -n $ISMUTED ]]; then
		pactl set-source-mute @DEFAULT_SOURCE@ toggle && ${notify_cmd} -i "$iDIR/microphone.svg" "Microphone Switched ON" && echo 1 >/sys/class/leds/platform::micmute/brightness
	else
		pactl set-source-mute @DEFAULT_SOURCE@ toggle && ${notify_cmd} -i "$iDIR/microphone-mute.svg" "Microphone Switched OFF" && echo 0 >/sys/class/leds/platform::micmute/brightness
	fi
}

# Execute accordingly
if [[ -x $(which pactl) ]]; then
	if [[ "$1" == "--get" ]]; then
		get_volume
	elif [[ "$1" == "--inc" ]]; then
		inc_volume
	elif [[ "$1" == "--dec" ]]; then
		dec_volume
	elif [[ "$1" == "--toggle" ]]; then
		toggle_mute
	elif [[ "$1" == "--toggle-mic" ]]; then
		toggle_mic
	else
		echo "$(get_volume)"%
	fi
else
	${notify_cmd} "'WirePlumber' is not installed."
fi
